apiVersion: apps/v1
kind: Deployment
metadata:
  name: sementic-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sementic-frontend
  template:
    metadata:
      labels:
        app: sementic-frontend
    spec:
      containers:
        - name: sementic-frontend
          image: DOCKER_USERNAME/sementic-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sementic-frontend
spec:
  type: LoadBalancer
  selector:
    app: sementic-frontend
  ports:
    - port: 80
      targetPort: 80
