name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Search Service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/search-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/search-service:latest

      - name: Build and Push Embedding Service
        uses: docker/build-push-action@v5
        with:
          context: ./backend/embedding-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/embedding-service:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./sementic-frontend
          push: true

          tags: ${{ secrets.DOCKER_USERNAME }}/sementic-frontend:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Replace Docker Username in Manifests
        run: |
          sed -i "s|DOCKER_USERNAME|$DOCKER_USERNAME|g" k8s/search-deployment.yaml
          sed -i "s|DOCKER_USERNAME|$DOCKER_USERNAME|g" k8s/embedding-deployment.yaml
          sed -i "s|DOCKER_USERNAME|$DOCKER_USERNAME|g" k8s/frontend-deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment/search-service
          kubectl rollout restart deployment/embedding-service
          kubectl rollout restart deployment/sementic-frontend
